Partners:
    - Name: S
      IP: 127.0.0.1
      Port: 5005

LocalRole:
  Name: C
  IP: 127.0.0.1
  Port: 5004

ScribblePath:
   FileName: "C:/cygwin64/home/rhu/code/eclipse/scribble/github.com/rumineykova/scribble-java/scribblec.bat"

   C:\cygwin64\home\rhu\code\vs\scribble\github.com\rumineykova\Sast\Examples\Fibonacci